services:
  apps:
    build: ./
    ports:
      - "3000:3000"

  apps-dev:
    build: ./docker/nodejs
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: /bin/sh ./scripts/dev/dev.local.sh
    depends_on:
      - database

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password