services:
  apps:
    build: ./
    ports:
      - "3000:3000"

  apps-dev:
    build: ./docker/nodejs
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: /bin/sh ./scripts/dev/dev.local.sh
    depends_on:
      - database
    network_mode: host

  database:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/provision/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    network_mode: host
