name: CI
run-name: ${{ github.actor }} is running ${{ github.workflow }} on commit ${{ github.sha }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  DOCKER_TAG: ${{ secrets.DOCKER_USERNAME }}/team8:${{ github.sha }}
  IS_PUSH_TO_MAIN: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        if: ${{ env.IS_PUSH_TO_MAIN }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_TAG }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
  
  lint:
    runs-on: ubuntu-latest
    needs: build
    concurrency: 
      group: lint-${{ github.sha }}
      cancel-in-progress: true
    steps:
      - name: Run linter on workspace backend
        continue-on-error: true
        run: docker run ${{ env.IMAGE_NAME }} yarn workspace @team8/backend lint
      - name: Run linter on workspace frontend
        continue-on-error: true
        run: docker run ${{ env.IMAGE_NAME }} yarn workspace @team8/frontend lint
      - name: Run linter on workspace types
        continue-on-error: true
        run: docker run ${{ env.IMAGE_NAME }} yarn workspace @team8/types lint
      - name: Run linter on workspace constants
        continue-on-error: true
        run: docker run ${{ env.IMAGE_NAME }} yarn workspace @team8/constants lint
      - name: Run linter on workspace utils
        continue-on-error: true
        run: docker run ${{ env.IMAGE_NAME }} yarn workspace @team8/utils lint

  tests:
    runs-on: ubuntu-latest
    needs: build
    concurrency: 
      group: tests-${{ github.sha }}
      cancel-in-progress: true
    steps:
      - name: Run unit tests on backend
        run: docker run ${{ env.IMAGE_NAME }} yarn workspace @team8/backend test:unit
