name: Run command from docker container with prod config
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to run'
        required: true
        default: 'echo "No command specified"'

env:
  DOCKER_TAG: ${{ secrets.DOCKER_USERNAME }}/team8:${{ github.sha }}

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.DOCKER_TAG }}
      - name: Run command
        run: docker run ${{ env.DOCKER_TAG }} ${{ github.event.inputs.command }}