name: test
run-name: ${{ github.actor }} is testing
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start up dev environment
        run: make dev
      - name: Run backend unit test
        run: docker-compose exec apps-dev sh -c "yarn workspace @team8/backend test:unit"